[package]
name = "mh-z19b-firmware"
version = "0.1.0"
authors = ["Vadim Kaushan <admin@disasm.info>"]
edition = "2018"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
panic-halt = "0.2.0"
stm32f0xx-hal = { version = "0.18.0", features = ["rt", "stm32f051"] }
